import { Lead, ChatMessage, VoiceTranscript } from './types'

const chatMessages1: ChatMessage[] = [
  {
    id: 'c1',
    role: 'assistant',
    content: 'Hello! Welcome to Classy Voyage. How can I help you plan your perfect trip today?',
    timestamp: new Date('2024-01-15T10:00:00'),
  },
  {
    id: 'c2',
    role: 'user',
    content: 'Hi! I\'m looking to book a flight from New York to Paris for a romantic getaway.',
    timestamp: new Date('2024-01-15T10:00:30'),
  },
  {
    id: 'c3',
    role: 'assistant',
    content: 'How wonderful! Paris is perfect for a romantic getaway. When are you planning to travel, and how many passengers?',
    timestamp: new Date('2024-01-15T10:01:00'),
  },
  {
    id: 'c4',
    role: 'user',
    content: 'We\'re looking at departing March 15th and returning March 22nd. It will be 2 adults.',
    timestamp: new Date('2024-01-15T10:02:00'),
  },
  {
    id: 'c5',
    role: 'assistant',
    content: 'Perfect! Would you prefer economy, premium economy, business, or first class for your romantic journey?',
    timestamp: new Date('2024-01-15T10:02:30'),
  },
  {
    id: 'c6',
    role: 'user',
    content: 'Business class would be ideal. What are the options?',
    timestamp: new Date('2024-01-15T10:03:00'),
  },
]

const voiceTranscripts1: VoiceTranscript[] = [
  {
    id: 'v1',
    speaker: 'agent',
    text: 'Thank you for calling Classy Voyage. My name is Sarah. How may I assist you today?',
    timestamp: new Date('2024-01-16T14:00:00'),
    duration: 5,
  },
  {
    id: 'v2',
    speaker: 'customer',
    text: 'Hi Sarah, I need to book a business trip to Tokyo as soon as possible.',
    timestamp: new Date('2024-01-16T14:00:05'),
    duration: 4,
  },
  {
    id: 'v3',
    speaker: 'agent',
    text: 'I\'d be happy to help with that. When do you need to depart, and how long will you be staying?',
    timestamp: new Date('2024-01-16T14:00:09'),
    duration: 5,
  },
  {
    id: 'v4',
    speaker: 'customer',
    text: 'I need to leave this Friday and return the following Tuesday. Five nights total.',
    timestamp: new Date('2024-01-16T14:00:14'),
    duration: 4,
  },
]

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '+1 (555) 123-4567',
    status: 'qualified',
    interactionType: 'chat',
    chatHistory: chatMessages1,
    flightInquiry: {
      origin: 'New York (JFK)',
      destination: 'Paris (CDG)',
      departureDate: '2024-03-15',
      returnDate: '2024-03-22',
      passengers: {
        adults: 2,
        children: 0,
        infants: 0,
      },
      class: 'business',
      budget: '$8,000 - $12,000',
    },
    aiSummary: 'High-value lead seeking business class flights to Paris for romantic getaway. Budget-conscious but willing to pay for comfort. Responsive and engaged in conversation.',
    leadScore: 85,
    createdAt: new Date('2024-01-15T10:00:00'),
    updatedAt: new Date('2024-01-15T10:15:00'),
  },
  {
    id: 'lead-002',
    name: 'Michael Chen',
    email: 'michael.chen@techcorp.com',
    phone: '+1 (555) 234-5678',
    status: 'proposal',
    interactionType: 'voice',
    voiceTranscripts: voiceTranscripts1,
    flightInquiry: {
      origin: 'San Francisco (SFO)',
      destination: 'Tokyo (NRT)',
      departureDate: '2024-01-19',
      returnDate: '2024-01-24',
      passengers: {
        adults: 1,
        children: 0,
        infants: 0,
      },
      class: 'business',
      budget: 'Corporate account',
    },
    aiSummary: 'Urgent business travel requirement. Corporate traveler with established budget. Time-sensitive booking needed.',
    leadScore: 92,
    createdAt: new Date('2024-01-16T14:00:00'),
    updatedAt: new Date('2024-01-16T14:20:00'),
  },
  {
    id: 'lead-003',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@email.com',
    phone: '+1 (555) 345-6789',
    status: 'new',
    interactionType: 'chat',
    chatHistory: [
      {
        id: 'c7',
        role: 'assistant',
        content: 'Welcome to Classy Voyage! How can I help you today?',
        timestamp: new Date('2024-01-17T09:00:00'),
      },
      {
        id: 'c8',
        role: 'user',
        content: 'I\'m interested in a family vacation to Orlando.',
        timestamp: new Date('2024-01-17T09:00:30'),
      },
    ],
    flightInquiry: {
      origin: 'Chicago (ORD)',
      destination: 'Orlando (MCO)',
      departureDate: '2024-04-10',
      returnDate: '2024-04-17',
      passengers: {
        adults: 2,
        children: 2,
        infants: 0,
      },
      class: 'economy',
      budget: '$2,000 - $3,000',
    },
    leadScore: 45,
    createdAt: new Date('2024-01-17T09:00:00'),
    updatedAt: new Date('2024-01-17T09:05:00'),
  },
  {
    id: 'lead-004',
    name: 'David Thompson',
    email: 'david.t@email.com',
    phone: '+1 (555) 456-7890',
    status: 'contacted',
    interactionType: 'voice',
    voiceTranscripts: [
      {
        id: 'v5',
        speaker: 'agent',
        text: 'Good afternoon! Thank you for calling Classy Voyage.',
        timestamp: new Date('2024-01-17T15:00:00'),
        duration: 3,
      },
      {
        id: 'v6',
        speaker: 'customer',
        text: 'Hi, I want to book first class tickets to Dubai for my anniversary.',
        timestamp: new Date('2024-01-17T15:00:03'),
        duration: 4,
      },
    ],
    flightInquiry: {
      origin: 'Los Angeles (LAX)',
      destination: 'Dubai (DXB)',
      departureDate: '2024-05-20',
      returnDate: '2024-05-30',
      passengers: {
        adults: 2,
        children: 0,
        infants: 0,
      },
      class: 'first-class',
      budget: 'Premium - no limit',
    },
    aiSummary: 'Luxury travel inquiry for anniversary celebration. Premium customer segment.',
    leadScore: 95,
    createdAt: new Date('2024-01-17T15:00:00'),
    updatedAt: new Date('2024-01-17T15:10:00'),
  },
  {
    id: 'lead-005',
    name: 'Jessica Park',
    email: 'jessica.park@email.com',
    phone: '+1 (555) 567-8901',
    status: 'negotiation',
    interactionType: 'chat',
    chatHistory: [
      {
        id: 'c9',
        role: 'user',
        content: 'I need flights to London for a conference.',
        timestamp: new Date('2024-01-18T11:00:00'),
      },
    ],
    flightInquiry: {
      origin: 'Boston (BOS)',
      destination: 'London (LHR)',
      departureDate: '2024-02-28',
      returnDate: '2024-03-05',
      passengers: {
        adults: 1,
        children: 0,
        infants: 0,
      },
      class: 'premium-economy',
      budget: '$1,500 - $2,500',
    },
    leadScore: 72,
    createdAt: new Date('2024-01-18T11:00:00'),
    updatedAt: new Date('2024-01-18T11:30:00'),
  },
]
